apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: test-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    metadata:
      annotations:
        abc: "def"
    spec:
      template:
        metadata:
          annotations:
            abc: "def"
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure